TEXT_OUTPUT = False
TREE_SIMPLE = False
TREE_DETAILED = True

DEBUG = True

# DIFFLIB
DIFFLIB_NUMBER_OF_RESULTS = 10
DIFFLIB_CUTOFF = 0.6

# RAPIDFUZZ
RAPIDFUZZ_NUMBER_OF_RESULTS = 2
RAPIDFUZZ_CUTOFF = 0.6